spring.application.name=pharmacy-web-service
server.port=2222

spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacyDataBase
spring.datasource.username=postgres
spring.datasource.password=Kizez22RD22@

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.jackson.serialization.fail-on-empty-beans=false
logging.level.com.zez_world.pharmacy_web_service=DEBUG


jwt.secret=your-secret-key-change-this-in-production
jwt.expiration=86400000